FROM guacamole/guacamole:latest

COPY logback.xml /opt/guacamole/logback.xml
COPY guacamole-auth-anyhow-aws-1.0-SNAPSHOT.jar /opt/guacamole/guacamole-auth-anyhow-aws-1.0-SNAPSHOT.jar
COPY guacamole-auth-openid-1.0.0.jar /opt/guacamole/guacamole-auth-openid-1.0.0.jar
COPY start.sh /opt/guacamole/bin/start.sh
